# Generated by Django 5.0.3 on 2024-06-04 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.waiter'),
        ),
        migrations.AddField(
            model_name='bills',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.orders'),
        ),
        migrations.AddField(
            model_name='product_restaurant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.products'),
        ),
        migrations.AddField(
            model_name='products_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.orders'),
        ),
        migrations.AddField(
            model_name='products_order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.products'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product_restaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='tables_restaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='tables_restaurant',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.tables'),
        ),
        migrations.AddField(
            model_name='orders',
            name='tableRestaruant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.tables_restaurant'),
        ),
        migrations.AddField(
            model_name='tip_waiter',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.bills'),
        ),
        migrations.AddField(
            model_name='tip_waiter',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.waiter'),
        ),
    ]
