# Generated by Django 5.0.3 on 2024-06-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_bills_bill_rename_orders_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='final_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='tip_percent',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=2),
        ),
    ]
