# Generated by Django 5.0.3 on 2024-06-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='charge',
            field=models.CharField(choices=[('MG', 'MANAGER'), ('AT', 'ADMINTABLES'), ('EX', 'EXTRA')], default='EX', max_length=20),
        ),
    ]
